### ISSUE TITLE
cannot run lora.cc file

### ISSUE THREAD

**Issue by nurdila88** [networkedsystems/lora-ns3#11]
may u help me to solve this problem..i cant run this simulation..there is error..

program 'src/lora/examples/lora' not found; available programs are: ['aodv', 'src/aodv/examples/aodv', 'three-gpp-http-example', 'src/applications/examples/three-gpp-http-example', 'csma-bridge', 'src/bridge/examples/csma-bridge', 'csma-bridge-one-hop', 'src/bridge/examples/csma-bridge-one-hop', 'buildings-pathloss-profiler', 'src/buildings/examples/buildings-pathloss-profiler', 'outdoor-random-walk-example', 'src/buildings/examples/outdoor-random-walk-example', 'config-store-save', 'src/config-store/examples/config-store-save', 'main-callback', 'src/core/examples/main-callback', 'sample-simulator', 'src/core/examples/sample-simulator', 'main-ptr', 'src/core/examples/main-ptr', 'main-random-variable-stream', 'src/core/examples/main-random-variable-stream', 'sample-random-variable', 'src/core/examples/sample-random-variable', 'sample-random-variable-stream', 'src/core/examples/sample-random-variable-stream', 'command-line-example', 'src/core/examples/command-line-example', 'hash-example', 'src/core/examples/hash-example', 'sample-log-time-format', 'src/core/examples/sample-log-time-format', 'test-string-value-formatting', 'src/core/examples/test-string-value-formatting', 'sample-show-progress', 'src/core/examples/sample-show-progress', 'empirical-random-variable-example', 'src/core/examples/empirical-random-variable-example', 'system-path-examples', 'src/core/examples/system-path-examples', 'fatal-example', 'src/core/examples/fatal-example', 'main-test-sync', 'src/core/examples/main-test-sync', 'csma-one-subnet', 'src/csma/examples/csma-one-subnet', 'csma-broadcast', 'src/csma/examples/csma-broadcast', 'csma-packet-socket', 'src/csma/examples/csma-packet-socket', 'csma-multicast', 'src/csma/examples/csma-multicast', 'csma-raw-ip-socket', 'src/csma/examples/csma-raw-ip-socket', 'csma-ping', 'src/csma/examples/csma-ping', 'csma-star', 'src/csma-layout/examples/csma-star', 'dsdv-manet', 'src/dsdv/examples/dsdv-manet', 'dsr', 'src/dsr/examples/dsr', 'li-ion-energy-source', 'src/energy/examples/li-ion-energy-source', 'rv-battery-model-test', 'src/energy/examples/rv-battery-model-test', 'basic-energy-model-test', 'src/energy/examples/basic-energy-model-test', 'dummy-network', 'src/fd-net-device/examples/dummy-network', 'fd2fd-onoff', 'src/fd-net-device/examples/fd2fd-onoff', 'realtime-dummy-network', 'src/fd-net-device/examples/realtime-dummy-network', 'realtime-fd2fd-onoff', 'src/fd-net-device/examples/realtime-fd2fd-onoff', 'fd-emu-ping', 'src/fd-net-device/examples/fd-emu-ping', 'fd-emu-onoff', 'src/fd-net-device/examples/fd-emu-onoff', 'fd-emu-tc', 'src/fd-net-device/examples/fd-emu-tc', 'fd-emu-send', 'src/fd-net-device/examples/fd-emu-send', 'fd-emu-udp-echo', 'src/fd-net-device/examples/fd-emu-udp-echo', 'fd-tap-ping', 'src/fd-net-device/examples/fd-tap-ping', 'fd-tap-ping6', 'src/fd-net-device/examples/fd-tap-ping6', 'main-simple', 'src/internet/examples/main-simple', 'dhcp-example', 'src/internet-apps/examples/dhcp-example', 'traceroute-example', 'src/internet-apps/examples/traceroute-example', 'lr-wpan-packet-print', 'src/lr-wpan/examples/lr-wpan-packet-print', 'lr-wpan-phy-test', 'src/lr-wpan/examples/lr-wpan-phy-test', 'lr-wpan-data', 'src/lr-wpan/examples/lr-wpan-data', 'lr-wpan-error-model-plot', 'src/lr-wpan/examples/lr-wpan-error-model-plot', 'lr-wpan-error-distance-plot', 'src/lr-wpan/examples/lr-wpan-error-distance-plot', 'lr-wpan-mlme', 'src/lr-wpan/examples/lr-wpan-mlme', 'lena-cqi-threshold', 'src/lte/examples/lena-cqi-threshold', 'lena-dual-stripe', 'src/lte/examples/lena-dual-stripe', 'lena-fading', 'src/lte/examples/lena-fading', 'lena-intercell-interference', 'src/lte/examples/lena-intercell-interference', 'lena-ipv6-addr-conf', 'src/lte/examples/lena-ipv6-addr-conf', 'lena-ipv6-ue-rh', 'src/lte/examples/lena-ipv6-ue-rh', 'lena-ipv6-ue-ue', 'src/lte/examples/lena-ipv6-ue-ue', 'lena-pathloss-traces', 'src/lte/examples/lena-pathloss-traces', 'lena-profiling', 'src/lte/examples/lena-profiling', 'lena-rem', 'src/lte/examples/lena-rem', 'lena-rem-sector-antenna', 'src/lte/examples/lena-rem-sector-antenna', 'lena-rlc-traces', 'src/lte/examples/lena-rlc-traces', 'lena-simple', 'src/lte/examples/lena-simple', 'lena-simple-epc', 'src/lte/examples/lena-simple-epc', 'lena-simple-epc-backhaul', 'src/lte/examples/lena-simple-epc-backhaul', 'lena-deactivate-bearer', 'src/lte/examples/lena-deactivate-bearer', 'lena-x2-handover', 'src/lte/examples/lena-x2-handover', 'lena-x2-handover-measures', 'src/lte/examples/lena-x2-handover-measures', 'lena-frequency-reuse', 'src/lte/examples/lena-frequency-reuse', 'lena-distributed-ffr', 'src/lte/examples/lena-distributed-ffr', 'lena-uplink-power-control', 'src/lte/examples/lena-uplink-power-control', 'lena-radio-link-failure', 'src/lte/examples/lena-radio-link-failure', 'lena-simple-epc-emu', 'src/lte/examples/lena-simple-epc-emu', 'mesh', 'src/mesh/examples/mesh', 'main-grid-topology', 'src/mobility/examples/main-grid-topology', 'main-random-topology', 'src/mobility/examples/main-random-topology', 'main-random-walk', 'src/mobility/examples/main-random-walk', 'mobility-trace-example', 'src/mobility/examples/mobility-trace-example', 'ns2-mobility-trace', 'src/mobility/examples/ns2-mobility-trace', 'bonnmotion-ns2-example', 'src/mobility/examples/bonnmotion-ns2-example', 'dumbbell-animation', 'src/netanim/examples/dumbbell-animation', 'grid-animation', 'src/netanim/examples/grid-animation', 'star-animation', 'src/netanim/examples/star-animation', 'wireless-animation', 'src/netanim/examples/wireless-animation', 'uan-animation', 'src/netanim/examples/uan-animation', 'colors-link-description', 'src/netanim/examples/colors-link-description', 'resources-counters', 'src/netanim/examples/resources-counters', 'main-packet-header', 'src/network/examples/main-packet-header', 'main-packet-tag', 'src/network/examples/main-packet-tag', 'packet-socket-apps', 'src/network/examples/packet-socket-apps', 'lollipop-comparisions', 'src/network/examples/lollipop-comparisions', 'nix-simple', 'src/nix-vector-routing/examples/nix-simple', 'nms-p2p-nix', 'src/nix-vector-routing/examples/nms-p2p-nix', 'simple-point-to-point-olsr', 'src/olsr/examples/simple-point-to-point-olsr', 'olsr-hna', 'src/olsr/examples/olsr-hna', 'main-attribute-value', 'src/point-to-point/examples/main-attribute-value', 'main-propagation-loss', 'src/propagation/examples/main-propagation-loss', 'jakes-propagation-model-example', 'src/propagation/examples/jakes-propagation-model-example', 'example-sixlowpan', 'src/sixlowpan/examples/example-sixlowpan', 'example-ping-lr-wpan', 'src/sixlowpan/examples/example-ping-lr-wpan', 'example-ping-lr-wpan-beacon', 'src/sixlowpan/examples/example-ping-lr-wpan-beacon', 'example-ping-lr-wpan-mesh-under', 'src/sixlowpan/examples/example-ping-lr-wpan-mesh-under', 'adhoc-aloha-ideal-phy', 'src/spectrum/examples/adhoc-aloha-ideal-phy', 'adhoc-aloha-ideal-phy-matrix-propagation-loss-model', 'src/spectrum/examples/adhoc-aloha-ideal-phy-matrix-propagation-loss-model', 'adhoc-aloha-ideal-phy-with-microwave-oven', 'src/spectrum/examples/adhoc-aloha-ideal-phy-with-microwave-oven', 'tv-trans-example', 'src/spectrum/examples/tv-trans-example', 'tv-trans-regional-example', 'src/spectrum/examples/tv-trans-regional-example', 'three-gpp-channel-example', 'src/spectrum/examples/three-gpp-channel-example', 'gnuplot-example', 'src/stats/examples/gnuplot-example', 'double-probe-example', 'src/stats/examples/double-probe-example', 'time-probe-example', 'src/stats/examples/time-probe-example', 'gnuplot-aggregator-example', 'src/stats/examples/gnuplot-aggregator-example', 'gnuplot-helper-example', 'src/stats/examples/gnuplot-helper-example', 'file-aggregator-example', 'src/stats/examples/file-aggregator-example', 'file-helper-example', 'src/stats/examples/file-helper-example', 'tap-csma', 'src/tap-bridge/examples/tap-csma', 'tap-csma-virtual-machine', 'src/tap-bridge/examples/tap-csma-virtual-machine', 'tap-wifi-virtual-machine', 'src/tap-bridge/examples/tap-wifi-virtual-machine', 'tap-wifi-dumbbell', 'src/tap-bridge/examples/tap-wifi-dumbbell', 'topology-example-sim', 'src/topology-read/examples/topology-example-sim', 'red-tests', 'src/traffic-control/examples/red-tests', 'red-vs-ared', 'src/traffic-control/examples/red-vs-ared', 'adaptive-red-tests', 'src/traffic-control/examples/adaptive-red-tests', 'pfifo-vs-red', 'src/traffic-control/examples/pfifo-vs-red', 'codel-vs-pfifo-basic-test', 'src/traffic-control/examples/codel-vs-pfifo-basic-test', 'codel-vs-pfifo-asymmetric', 'src/traffic-control/examples/codel-vs-pfifo-asymmetric', 'pie-example', 'src/traffic-control/examples/pie-example', 'fqcodel-l4s-example', 'src/traffic-control/examples/fqcodel-l4s-example', 'uan-cw-example', 'src/uan/examples/uan-cw-example', 'uan-rc-example', 'src/uan/examples/uan-rc-example', 'uan-raw-example', 'src/uan/examples/uan-raw-example', 'uan-ipv4-example', 'src/uan/examples/uan-ipv4-example', 'uan-ipv6-example', 'src/uan/examples/uan-ipv6-example', 'uan-6lowpan-example', 'src/uan/examples/uan-6lowpan-example', 'virtual-net-device', 'src/virtual-net-device/examples/virtual-net-device', 'wave-simple-80211p', 'src/wave/examples/wave-simple-80211p', 'wave-simple-device', 'src/wave/examples/wave-simple-device', 'vanet-routing-compare', 'src/wave/examples/vanet-routing-compare', 'wifi-phy-test', 'src/wifi/examples/wifi-phy-test', 'wifi-test-interference-helper', 'src/wifi/examples/wifi-test-interference-helper', 'wifi-manager-example', 'src/wifi/examples/wifi-manager-example', 'wifi-trans-example', 'src/wifi/examples/wifi-trans-example', 'wifi-phy-configuration', 'src/wifi/examples/wifi-phy-configuration', 'wifi-bianchi', 'src/wifi/examples/wifi-bianchi', 'wimax-ipv4', 'src/wimax/examples/wimax-ipv4', 'wimax-multicast', 'src/wimax/examples/wimax-multicast', 'wimax-simple', 'src/wimax/examples/wimax-simple', 'matrix-topology', 'examples/matrix-topology/matrix-topology', 'simple-error-model', 'examples/error-model/simple-error-model', 'socket-bound-static-routing', 'examples/socket/socket-bound-static-routing', 'socket-bound-tcp-static-routing', 'examples/socket/socket-bound-tcp-static-routing', 'socket-options-ipv4', 'examples/socket/socket-options-ipv4', 'socket-options-ipv6', 'examples/socket/socket-options-ipv6', 'energy-model-example', 'examples/energy/energy-model-example', 'energy-model-with-harvesting-example', 'examples/energy/energy-model-with-harvesting-example', 'udp-echo', 'examples/udp/udp-echo', 'udp-client-server', 'examples/udp-client-server/udp-client-server', 'udp-trace-client-server', 'examples/udp-client-server/udp-trace-client-server', 'object-names', 'examples/naming/object-names', 'hello-simulator', 'examples/tutorial/hello-simulator', 'first', 'examples/tutorial/first', 'second', 'examples/tutorial/second', 'third', 'examples/tutorial/third', 'fourth', 'examples/tutorial/fourth', 'fifth', 'examples/tutorial/fifth', 'sixth', 'examples/tutorial/sixth', 'seventh', 'examples/tutorial/seventh', 'traffic-control', 'examples/traffic-control/traffic-control', 'queue-discs-benchmark', 'examples/traffic-control/queue-discs-benchmark', 'red-vs-fengadaptive', 'examples/traffic-control/red-vs-fengadaptive', 'red-vs-nlred', 'examples/traffic-control/red-vs-nlred', 'tbf-example', 'examples/traffic-control/tbf-example', 'cobalt-vs-codel', 'examples/traffic-control/cobalt-vs-codel', 'dynamic-global-routing', 'examples/routing/dynamic-global-routing', 'static-routing-slash32', 'examples/routing/static-routing-slash32', 'global-routing-slash32', 'examples/routing/global-routing-slash32', 'global-injection-slash32', 'examples/routing/global-injection-slash32', 'simple-global-routing', 'examples/routing/simple-global-routing', 'simple-alternate-routing', 'examples/routing/simple-alternate-routing', 'mixed-global-routing', 'examples/routing/mixed-global-routing', 'simple-routing-ping6', 'examples/routing/simple-routing-ping6', 'manet-routing-compare', 'examples/routing/manet-routing-compare', 'ripng-simple-network', 'examples/routing/ripng-simple-network', 'rip-simple-network', 'examples/routing/rip-simple-network', 'global-routing-multi-switch-plus-router', 'examples/routing/global-routing-multi-switch-plus-router', 'simple-multicast-flooding', 'examples/routing/simple-multicast-flooding', 'tcp-large-transfer', 'examples/tcp/tcp-large-transfer', 'tcp-nsc-lfn', 'examples/tcp/tcp-nsc-lfn', 'tcp-nsc-zoo', 'examples/tcp/tcp-nsc-zoo', 'tcp-star-server', 'examples/tcp/tcp-star-server', 'star', 'examples/tcp/star', 'tcp-bulk-send', 'examples/tcp/tcp-bulk-send', 'tcp-pcap-nanosec-example', 'examples/tcp/tcp-pcap-nanosec-example', 'tcp-nsc-comparison', 'examples/tcp/tcp-nsc-comparison', 'tcp-variants-comparison', 'examples/tcp/tcp-variants-comparison', 'tcp-pacing', 'examples/tcp/tcp-pacing', 'dctcp-example', 'examples/tcp/dctcp-example', 'tcp-linux-reno', 'examples/tcp/tcp-linux-reno', 'realtime-udp-echo', 'examples/realtime/realtime-udp-echo', 'wifi-example-sim', 'examples/stats/wifi-example-sim', 'icmpv6-redirect', 'examples/ipv6/icmpv6-redirect', 'ping6', 'examples/ipv6/ping6', 'radvd', 'examples/ipv6/radvd', 'radvd-two-prefix', 'examples/ipv6/radvd-two-prefix', 'test-ipv6', 'examples/ipv6/test-ipv6', 'fragmentation-ipv6', 'examples/ipv6/fragmentation-ipv6', 'fragmentation-ipv6-two-MTU', 'examples/ipv6/fragmentation-ipv6-two-MTU', 'loose-routing-ipv6', 'examples/ipv6/loose-routing-ipv6', 'wsn-ping6', 'examples/ipv6/wsn-ping6', 'mixed-wired-wireless', 'examples/wireless/mixed-wired-wireless', 'wifi-adhoc', 'examples/wireless/wifi-adhoc', 'wifi-clear-channel-cmu', 'examples/wireless/wifi-clear-channel-cmu', 'wifi-ap', 'examples/wireless/wifi-ap', 'wifi-wired-bridging', 'examples/wireless/wifi-wired-bridging', 'wifi-multirate', 'examples/wireless/wifi-multirate', 'wifi-simple-adhoc', 'examples/wireless/wifi-simple-adhoc', 'wifi-simple-adhoc-grid', 'examples/wireless/wifi-simple-adhoc-grid', 'wifi-simple-infra', 'examples/wireless/wifi-simple-infra', 'wifi-simple-interference', 'examples/wireless/wifi-simple-interference', 'wifi-blockack', 'examples/wireless/wifi-blockack', 'wifi-dsss-validation', 'examples/wireless/wifi-dsss-validation', 'wifi-ofdm-validation', 'examples/wireless/wifi-ofdm-validation', 'wifi-ofdm-ht-validation', 'examples/wireless/wifi-ofdm-ht-validation', 'wifi-ofdm-vht-validation', 'examples/wireless/wifi-ofdm-vht-validation', 'wifi-hidden-terminal', 'examples/wireless/wifi-hidden-terminal', 'wifi-ht-network', 'examples/wireless/wifi-ht-network', 'wifi-vht-network', 'examples/wireless/wifi-vht-network', 'wifi-timing-attributes', 'examples/wireless/wifi-timing-attributes', 'wifi-sleep', 'examples/wireless/wifi-sleep', 'wifi-power-adaptation-distance', 'examples/wireless/wifi-power-adaptation-distance', 'wifi-power-adaptation-interference', 'examples/wireless/wifi-power-adaptation-interference', 'wifi-rate-adaptation-distance', 'examples/wireless/wifi-rate-adaptation-distance', 'wifi-aggregation', 'examples/wireless/wifi-aggregation', 'wifi-txop-aggregation', 'examples/wireless/wifi-txop-aggregation', 'wifi-simple-ht-hidden-stations', 'examples/wireless/wifi-simple-ht-hidden-stations', 'wifi-80211n-mimo', 'examples/wireless/wifi-80211n-mimo', 'wifi-mixed-network', 'examples/wireless/wifi-mixed-network', 'wifi-tcp', 'examples/wireless/wifi-tcp', 'wifi-80211e-txop', 'examples/wireless/wifi-80211e-txop', 'wifi-spectrum-per-example', 'examples/wireless/wifi-spectrum-per-example', 'wifi-spectrum-per-interference', 'examples/wireless/wifi-spectrum-per-interference', 'wifi-spectrum-saturation-example', 'examples/wireless/wifi-spectrum-saturation-example', 'wifi-ofdm-he-validation', 'examples/wireless/wifi-ofdm-he-validation', 'wifi-he-network', 'examples/wireless/wifi-he-network', 'wifi-multi-tos', 'examples/wireless/wifi-multi-tos', 'wifi-backward-compatibility', 'examples/wireless/wifi-backward-compatibility', 'wifi-pcf', 'examples/wireless/wifi-pcf', 'wifi-spatial-reuse', 'examples/wireless/wifi-spatial-reuse', 'subdir', 'scratch/subdir/subdir', 'scratch-simulator', 'scratch/scratch-simulator', 'test-runner', 'utils/test-runner', 'bench-simulator', 'utils/bench-simulator', 'bench-packets', 'utils/bench-packets', 'print-introspected-doxygen', 'utils/print-introspected-doxygen', 'tap-device-creator', 'src/fd-net-device/tap-device-creator', 'raw-sock-creator', 'src/fd-net-device/raw-sock-creator', 'tap-creator', 'src/tap-bridge/tap-creator']

**Comment by nurdila88** [comment]
Modules built:
antenna                   aodv                      applications
bridge                    buildings                 config-store
core                      csma                      csma-layout
dsdv                      dsr                       energy
fd-net-device             flow-monitor              internet
internet-apps             lora (no Python)          lr-wpan
lte                       mesh                      mobility
netanim                   network                   nix-vector-routing
olsr                      point-to-point            point-to-point-layout
propagation               sixlowpan                 spectrum
stats                     tap-bridge                test (no Python)
topology-read             traffic-control           uan
virtual-net-device        wave                      wifi
wimax

Modules not built (see ns-3 tutorial for explanation):
brite                     click                     dpdk-net-device
mpi                       openflow                  visualizer

The test suite was not run because an unknown test suite name was requested.

**Comment by Orienfish** [comment]
I think the reason is, in the ''lora-ns3/wscript" file they offer, they did not enable building examples for this lora module.
If you just want to run that lora.cc example, you can copy it under the "scratch" directory in ns3, then simply run it like
`./waf --run lora`.

**Comment by nurdila88** [comment]
i already do like what u say..but it still cannot run


s3@ubuntu:~/Desktop/ns3/ns-allinone-3.32/ns-3.32$ cd scratch
ns3@ubuntu:~/Desktop/ns3/ns-allinone-3.32/ns-3.32/scratch$ cd lora
ns3@ubuntu:~/Desktop/ns3/ns-allinone-3.32/ns-3.32/scratch/lora$ cd ../
ns3@ubuntu:~/Desktop/ns3/ns-allinone-3.32/ns-3.32/src$ cd ../
ns3@ubuntu:~/Desktop/ns3/ns-allinone-3.32/ns-3.32$ ./waf --run lora
Traceback (most recent call last):
  File "/home/ns3/Desktop/ns3/ns-allinone-3.32/ns-3.32/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Scripting.py", line 119, in waf_entry_point
    run_commands()
  File "/home/ns3/Desktop/ns3/ns-allinone-3.32/ns-3.32/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Scripting.py", line 178, in run_commands
    parse_options()
  File "/home/ns3/Desktop/ns3/ns-allinone-3.32/ns-3.32/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Scripting.py", line 158, in parse_options
    ctx.execute()
  File "/home/ns3/Desktop/ns3/ns-allinone-3.32/ns-3.32/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Options.py", line 198, in execute
    super(OptionsContext,self).execute()
  File "/home/ns3/Desktop/ns3/ns-allinone-3.32/ns-3.32/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Context.py", line 85, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/ns3/Desktop/ns3/ns-allinone-3.32/ns-3.32/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Context.py", line 126, in recurse
    user_function(self)
  File "/home/ns3/Desktop/ns3/ns-allinone-3.32/ns-3.32/wscript", line 272, in options
    opt.recurse('src')
  File "/home/ns3/Desktop/ns3/ns-allinone-3.32/ns-3.32/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Context.py", line 126, in recurse
    user_function(self)
  File "/home/ns3/Desktop/ns3/ns-allinone-3.32/ns-3.32/src/wscript", line 51, in options
    opt.recurse(module, mandatory=False)
  File "/home/ns3/Desktop/ns3/ns-allinone-3.32/ns-3.32/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Context.py", line 120, in recurse
    wscript_module=load_module(node.abspath(),encoding=encoding)
  File "/home/ns3/Desktop/ns3/ns-allinone-3.32/ns-3.32/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Context.py", line 355, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/home/ns3/Desktop/ns3/ns-allinone-3.32/ns-3.32/src/lora/wscript", line 109
    if (bld.env['ENABLE_EXAMPLES']):
                                   ^
IndentationError: unindent does not match any outer indentation level
ns3@ubuntu:~/Desktop/ns3/ns-allinone-3.32/ns-3.32$

**Comment by nurdila88** [comment]
i still cannot run the lora example...


s3@ubuntu:~/Desktop/ns3/ns-allinone-3.32/ns-3.32$ cd scratch
ns3@ubuntu:~/Desktop/ns3/ns-allinone-3.32/ns-3.32/scratch$ cd lora
ns3@ubuntu:~/Desktop/ns3/ns-allinone-3.32/ns-3.32/scratch/lora$ cd ../
ns3@ubuntu:~/Desktop/ns3/ns-allinone-3.32/ns-3.32/src$ cd ../
ns3@ubuntu:~/Desktop/ns3/ns-allinone-3.32/ns-3.32$ ./waf --run lora
Traceback (most recent call last):
  File "/home/ns3/Desktop/ns3/ns-allinone-3.32/ns-3.32/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Scripting.py", line 119, in waf_entry_point
    run_commands()
  File "/home/ns3/Desktop/ns3/ns-allinone-3.32/ns-3.32/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Scripting.py", line 178, in run_commands
    parse_options()
  File "/home/ns3/Desktop/ns3/ns-allinone-3.32/ns-3.32/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Scripting.py", line 158, in parse_options
    ctx.execute()
  File "/home/ns3/Desktop/ns3/ns-allinone-3.32/ns-3.32/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Options.py", line 198, in execute
    super(OptionsContext,self).execute()
  File "/home/ns3/Desktop/ns3/ns-allinone-3.32/ns-3.32/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Context.py", line 85, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/ns3/Desktop/ns3/ns-allinone-3.32/ns-3.32/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Context.py", line 126, in recurse
    user_function(self)
  File "/home/ns3/Desktop/ns3/ns-allinone-3.32/ns-3.32/wscript", line 272, in options
    opt.recurse('src')
  File "/home/ns3/Desktop/ns3/ns-allinone-3.32/ns-3.32/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Context.py", line 126, in recurse
    user_function(self)
  File "/home/ns3/Desktop/ns3/ns-allinone-3.32/ns-3.32/src/wscript", line 51, in options
    opt.recurse(module, mandatory=False)
  File "/home/ns3/Desktop/ns3/ns-allinone-3.32/ns-3.32/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Context.py", line 120, in recurse
    wscript_module=load_module(node.abspath(),encoding=encoding)
  File "/home/ns3/Desktop/ns3/ns-allinone-3.32/ns-3.32/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Context.py", line 355, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/home/ns3/Desktop/ns3/ns-allinone-3.32/ns-3.32/src/lora/wscript", line 109
    if (bld.env['ENABLE_EXAMPLES']):
                                   ^
IndentationError: unindent does not match any outer indentation level
ns3@ubuntu:~/Desktop/ns3/ns-allinone-3.32/ns-3.32$

**Comment by nurdila88** [comment]
# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import os.path

def build(bld):
	obj = bld.create_ns3_module('lora', ['core', 'network', 'mobility', 'spectrum', 'propagation', 'energy'])
	obj.source = [
	  'helper/lora-helper.cc',
	  'helper/lora-energy-source-helper.cc',
	  'helper/lora-radio-energy-model-helper.cc',
	  'model/lora-error-model.cc',
	  'model/lora-radio-energy-model.cc',
	  'model/lora-phy.cc',
	  'model/lora-application.cc',
	  'model/lora-sink-application.cc',
	  'model/lora-gw-phy.cc',
	  'model/lora-phy-header.cc',
	  'model/lora-mac-trailer.cc',
	  'model/lora-spectrum-signal-parameters.cc',
	  'model/lora-mac-header.cc',
	  'model/lora-mac-command.cc',
	  'model/lora-net-device.cc',
	  'model/lora-rs-net-device.cc',
	  'model/lora-rs-gw-net-device.cc',
	  'model/lora-gw-net-device.cc',
	  'model/lora-network.cc',
	  'model/lora-network-trailer.cc',
	  'model/lora-network-application.cc',
	  'model/lora-power-application.cc',
	  'model/lora-no-power-application.cc',
    'model/lora-sf-controller-application.cc',
	  'model/lora-test-application.cc',
	  'model/sf-mab.cc',
	  'model/commands/link-check-req.cc',
	  'model/commands/link-adr-ans.cc',
	  'model/commands/dev-status-ans.cc',
	  'model/commands/duty-cycle-ans.cc',
	  'model/commands/rx-param-setup-ans.cc',
	  'model/commands/new-channel-ans.cc',
	  'model/commands/rx-timing-setup-ans.cc',
	  'model/commands/link-check-ans.cc',
	  'model/commands/link-adr-req.cc',
	  'model/commands/dev-status-req.cc',
	  'model/commands/duty-cycle-req.cc',
	  'model/commands/rx-param-setup-req.cc',
	  'model/commands/new-channel-req.cc',
	  'model/commands/rx-timing-setup-req.cc',
	  'model/gw-trailer.cc',
		'model/noise-ism.cc',
	  'model/random-mixture.cc',
	  'model/mac32-address.cc'
		]

	obj.cxxflags=['-finstrument-functions']

	module_test = bld.create_ns3_module_test_library('lora')
	module_test.source = [
	]

	headers = bld(features='ns3header')
	headers.module = 'lora'
	headers.source = [
    'helper/lora-helper.h',
    'helper/lora-energy-source-helper.h',
    'helper/lora-radio-energy-model-helper.h',
    'model/lora-error-model.h',
    'model/lora-radio-energy-model.h',
    'model/lora-phy.h',
    'model/lora-application.h',
    'model/lora-sink-application.h',
    'model/lora-gw-phy.h',
    'model/lora-phy-header.h',
    'model/lora-spectrum-signal-parameters.h',
    'model/lora-mac-header.h',
    'model/lora-mac-command.h',
    'model/lora-mac-trailer.h',
    'model/lora-net-device.h',
    'model/lora-rs-net-device.h',
    'model/lora-rs-gw-net-device.h',
    'model/lora-gw-net-device.h',
    'model/lora-network.h',
    'model/lora-network-trailer.h',
    'model/lora-network-application.h',
    'model/lora-power-application.h',
    'model/lora-no-power-application.h',
    'model/lora-sf-controller-application.h',
    'model/lora-test-application.h',
	  'model/sf-mab.h',
    'model/commands/link-check-req.h',
    'model/commands/link-adr-ans.h',
    'model/commands/dev-status-ans.h',
    'model/commands/duty-cycle-ans.h',
    'model/commands/rx-param-setup-ans.h',
    'model/commands/new-channel-ans.h',
    'model/commands/rx-timing-setup-ans.h',
    'model/commands/link-check-ans.h',
    'model/commands/link-adr-req.h',
    'model/commands/dev-status-req.h',
    'model/commands/duty-cycle-req.h',
    'model/commands/rx-param-setup-req.h',
    'model/commands/new-channel-req.h',
    'model/commands/rx-timing-setup-req.h',
    'model/gw-trailer.h',
 		'model/noise-ism.h',
	  'model/random-mixture.h',
	  'model/mac32-address.h'
		]

  if (bld.env['ENABLE_EXAMPLES']):
      bld.recurse('examples')

	#bld.ns3_python_bindings()

**Comment by Orienfish** [comment]
Could you please keep the original `wscript` as it is - I mean, do not uncomment the two lines:
```
#  if (bld.env['ENABLE_EXAMPLES']):
#  bld.recurse('examples')
```
It seems the compiler is complaining about the indention for these two lines.
Then copy the `lora.cc` under `scratch` and run it.
Also, could you include the complete command you are using, and the output in a **readable** way? Otherwise it is really hard to view.
